In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)


[ 0.56070558 -1.26355156 -0.54739956  0.02090388  0.55421348]


In [3]:
print(a.shape) # rank 1 array, neither a row or vector

# doesnt behave consistently as a row or column vector

(5,)


In [4]:
print(a.T)

[ 0.56070558 -1.26355156 -0.54739956  0.02090388  0.55421348]


In [5]:
print(np.dot(a,a.T))

2.5181891206764364


In [12]:
# don't use data structures where the rank is (n,)
# instead use the following:
# column vector
a = np.random.randn(5,1)
print(a)
print(a.shape)

[[ 0.83191554]
 [ 0.04386629]
 [-0.31049345]
 [-0.48821836]
 [ 0.68927811]]
(5, 1)


In [8]:
print(a.T)

[[-0.68937931  2.21863578 -0.7968222   0.76735983  0.45928346]]


In [9]:
print(np.dot(a,a.T))

[[ 0.47524383 -1.5294816   0.54931274 -0.52900199 -0.31662052]
 [-1.5294816   4.92234472 -1.76785825  1.70249198  1.01898273]
 [ 0.54931274 -1.76785825  0.63492562 -0.61144935 -0.36596726]
 [-0.52900199  1.70249198 -0.61144935  0.58884111  0.35243568]
 [-0.31662052  1.01898273 -0.36596726  0.35243568  0.2109413 ]]
